/**
 * Standardized Application Error Codes
 */
const ERROR_CODES = Object.freeze({
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  RESTAURANT_INACTIVE: 'RESTAURANT_INACTIVE',
  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',
  MENU_ITEM_UNAVAILABLE: 'MENU_ITEM_UNAVAILABLE',
  MENU_ITEM_WRONG_RESTAURANT: 'MENU_ITEM_WRONG_RESTAURANT',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_ID: 'INVALID_ID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DRIVER_ASSIGNMENT_INVALID: 'DRIVER_ASSIGNMENT_INVALID',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND'
});

module.exports = {
  ERROR_CODES
};
